from __future__ import annotations

import json
from typing import Any


def render_few_shot_prompt(few_shot: list[dict[str, Any]]) -> str:
    if not few_shot:
        return ""
    return (
        "Additional behavioral examples generated by Ratchet. "
        "Use them to resolve similar patterns, but do not copy them unless the current case requires it.\n"
        f"{json.dumps(few_shot, indent=2, sort_keys=True)}"
    )
